######################################################################
# Automatically generated by qmake (3.0) ?? 8? 14 19:02:11 2017
######################################################################

TEMPLATE = app
TARGET = function_point
INCLUDEPATH += .

# Input
SOURCES += main.cpp
